Algoritmo "EX19-imparpar"

Var
   n,p: inteiro
   



Inicio
      Escreval ("---------------------------------")
      Escreval ("          IMPAR OU PAR")
      Escreval ("---------------------------------")
      Escreval ("")
      Escreva ("Digite um número. ")
               Leia (n)
      p<- n%2
      Se (p=0) entao
         Escreval ("O número",n," é par.")
      Senao
           Escreval ("O número",n," é impar.")
      Fimse
      
Fimalgoritmo